import Head from "next/head";
import { Suspense, useEffect } from "react";
import Feed from "../components/Feed";
import Headers from "../components/Headers";
import { PostinganPopup, UploadImgPopup } from "../components/Model";

export default function Home() {
    return (
        <div className=" h-screen bg-gray-50 overflow-auto">
            <Head>
                <title>Instagram - clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Headers />
            <Suspense
                fallback={
                    <div className=" h-screen w-full flex justify-center items-center bg-red-50">
                        Loading..
                    </div>
                }
            >
                <Feed />
            </Suspense>
            {/* model */}
            <UploadImgPopup />
            <PostinganPopup />
        </div>
    );
}
